#!/bin/sh
#set -x
curpath=`pwd`
runpath=$(dirname $(pwd))
argcount=$#
excname=$1
export LD_LIBRARY_PATH=../lib/

check_process_status()
{
    count=`ps -ef|grep -w $1|grep -v grep|grep -v check|wc -l`

    if [ ${count} -gt 0 ];then
        return 1
    fi
    return 0
}

echo "*************************************"
ser_list=`ls ${curpath}|grep camera_`
for service in $ser_list
do
    check_process_status ${service}
    if [ 0 -eq ${?} ]; then
        echo "the service ${service} is stop"
    else
        echo "the service ${service} is running"
    fi
done
echo "*************************************"