#!/bin/sh
#set -x
curpath=`pwd`
runpath=$(dirname $(pwd))
argcount=$#
excname=$1
export LD_LIBRARY_PATH=../lib/


check_process_status()
{
    count=`ps -ef|grep -w $1|grep -v grep|wc -l`

    if [ ${count} -eq 0 ];then
        echo "the service $1 is not running"
        return 1
    fi
    return 0
}

kill_the_process()
{
    process_list=`ps -ef|grep -w $1|grep -v grep|grep -v stop|awk -F ' ' '{print $2}'`
    if [ "t_${process_list}" == "t_" ]; then
        echo "the $1 is not running"
        return 0
    fi
    kill -9 ${process_list}
    return 0
}

if [ ${argcount} -eq 0 ];then
    echo "stop all avs service"
    ser_list=`ls ${curpath}|grep camera_`
    for service in $ser_list
    do
        check_process_status ${service}
        if [ 0 -eq ${?} ]; then
            echo "stop service ${service}"
            kill_the_process ${service}
        fi
    done
else
    if [[ ${excname} == camera_* ]];then
        check_process_status ${excname}
        if [ 0 -eq ${?} ]; then
            echo "stop service ${excname}"
            kill_the_process ${excname}
        fi
    fi
fi
